kind: Service
apiVersion: v1
metadata:
  name: dns-udp
spec:
  type: LoadBalancer
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    expose-service: dns
---
kind: Service
apiVersion: v1
metadata:
  name: dns-tcp
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
  selector:
    expose-service: dns
