apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound-dns
spec:
  selector:
    matchLabels:
      app: unbound-dns
  replicas: 4
  template:
    metadata:
      labels:
        app: unbound-dns
        expose-service: dns
    spec:
      containers:
        - name: unbound-dns
          image: registry.cn-shenzhen.aliyuncs.com/amphineko/unbound:1.13.1
          command:
            - /usr/local/sbin/unbound
            - -dc
            - /usr/local/etc/unbound/unbound.conf
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          # TODO: use `dig` to perform health check
          # readinessProbe:
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
            - mountPath: /usr/local/etc/unbound/unbound.conf
              name: unbound-config
              subPath: unbound.conf
              readOnly: true
      volumes:
        - name: unbound-config
          configMap:
            name: unbound-config
