apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: unbound
spec:
  selector:
    matchLabels:
      app: unbound
  replicas: 1
  template:
    metadata:
      labels:
        app: unbound
      namespace: unbound
    spec:
      containers:
        - name: unbound
          image: amphineko/unbound:1.13.1@sha256:b6bed96e31cdc27960f0c71b79729c16ea3d551f8fbb29e3f94b02e822252757
          command:
            - /usr/local/sbin/unbound
            - -dc
            - /usr/local/etc/unbound/unbound.conf
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          # TODO: use `dig` to perform health check
          # readinessProbe:
          resources:
            limits:
              cpu: "2000m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /usr/local/etc/unbound/unbound.conf
              name: unbound-config
              subPath: unbound.conf
              readOnly: true
      volumes:
        - name: unbound-config
          configMap:
            name: unbound-config
