---
apiVersion: v1
kind: Service
metadata:
  name: unbound-dns-udp
  namespace: unbound
spec:
  selector:
    app: unbound
  ports:
    - port: 53
      protocol: UDP
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: unbound-dns-tcp
  namespace: unbound
spec:
  selector:
    app: unbound
  ports:
    - port: 53
      protocol: TCP
  type: LoadBalancer
