# helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace -f values.yml

controller:
  ingressClassResource:
    default: true
  service:
    annotations:
      metallb.universe.tf/allow-shared-ip: foo
    type: LoadBalancer
  watchIngressWithoutClass: true
