apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-recursor
spec:
  selector:
    matchLabels:
      app: pdns-recursor
  replicas: 2
  template:
    metadata:
      labels:
        app: pdns-recursor
        expose-service: dns
    spec:
      containers:
        - name: pdns-recursor
          image: registry.cn-shenzhen.aliyuncs.com/amphineko/pdns-recursor:4.4.3-2
          env:
            - name: RECURSOR_allow_from
              value: "0.0.0.0/0, ::0/0"
            - name: RECURSOR_ecs_add_for
              value: "!0.0.0.0/0, !::/0"
            - name: RECURSOR_local_address
              value: "0.0.0.0, ::0"
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          # TODO: use `dig` to perform health check
          # readinessProbe:
          resources:
            limits:
              cpu: "500m"
              memory: "256M"
            requests:
              cpu: "0"
              memory: "0"
