---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: cloudflared
data:
  config.yml: |
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - service: http://haproxy-ingress.haproxy-controller.svc.cluster.local
    tunnel: <TUNNEL_ID>
  credentials.json: |
    {
      "AccountTag": "",
      "TunnelSecret": "",
      "TunnelID": "",
      "TunnelName": ""
    }
