---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2021.12.1
          command:
            - cloudflared
            - tunnel
            - --config
            - /etc/cloudflared/config.yml
            - --no-autoupdate
            - run
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "0"
              cpu: "0"
          volumeMounts:
            - mountPath: /etc/cloudflared/config.yml
              name: config
              subPath: config.yml
              readOnly: true
            - mountPath: /etc/cloudflared/credentials.json
              name: credentials
              subPath: credentials.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
        - name: credentials
          configMap:
            name: config
