---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-telemetry-magi-config
  namespace: system-telemetry
data:
  telegraf.conf: |+
    [[inputs.redfish]]
      address = "https://magi.local:443/"
      insecure_skip_verify = true

      username = "telegraf"
      password = "password"

      computer_system_id = "1"

    [[outputs.influxdb_v2]]
      bucket = "magi"
      organization = "system-telemetry"
      token = "token"
      urls = ["http://influxdb:8086"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf-telemetry-magi
  name: telegraf-telemetry-magi
  namespace: system-telemetry
spec:
  selector:
    matchLabels:
      app: telegraf-telemetry-magi
  template:
    metadata:
      labels:
        app: telegraf-telemetry-magi
      namespace: system-telemetry
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.16-alpine
          # readinessProbe:
          resources:
            limits:
              cpu: "1000m"
              memory: "128Mi"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: config
              subPath: telegraf.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: telegraf-telemetry-magi-config
